import { useEffect, useState } from "react";
import { parseApiError } from "@/api/errors";
import { useUpdateTrip } from "@/api/trips";
import { useBuses } from "@/api/buses";
import { useDriversList } from "@/api/drivers";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

const STATUSES = ["scheduled", "ongoing", "completed", "cancelled", "emergency"];

const EMPTY_FORM = {
  bus_id: "",
  driver_id: "",
  trip_date: "",
  departure_time: "",
  arrival_time: "",
  actual_departure: "",
  actual_arrival: "",
  status: STATUSES[0],
};

// Trips are legs generated by a shift, so this edits one — there's no "add a
// trip" any more; you add a shift and it produces its legs.
export default function TripFormDialog({ open, onOpenChange, trip }) {
  const [form, setForm] = useState(EMPTY_FORM);
  const [errors, setErrors] = useState({});
  const [generalError, setGeneralError] = useState("");
  const { data: busesPage } = useBuses(1);
  const buses = busesPage?.data ?? [];
  const { data: drivers } = useDriversList();
  const updateTrip = useUpdateTrip();

  useEffect(() => {
    if (!open || !trip) return;
    setForm({
      bus_id: trip.bus_id,
      driver_id: trip.driver_id,
      trip_date: trip.trip_date ?? "",
      departure_time: trip.departure_time?.slice(0, 5) ?? "",
      arrival_time: trip.arrival_time?.slice(0, 5) ?? "",
      actual_departure: trip.actual_departure?.slice(0, 16) ?? "",
      actual_arrival: trip.actual_arrival?.slice(0, 16) ?? "",
      status: trip.status,
    });
    setErrors({});
    setGeneralError("");
  }, [open, trip]);

  function handleChange(field, value) {
    setForm((f) => ({ ...f, [field]: value }));
  }

  async function handleSubmit(e) {
    e.preventDefault();
    setErrors({});
    setGeneralError("");

    try {
      await updateTrip.mutateAsync({
        id: trip.id,
        payload: {
          bus_id: Number(form.bus_id),
          driver_id: Number(form.driver_id),
          trip_date: form.trip_date,
          departure_time: form.departure_time || null,
          arrival_time: form.arrival_time || null,
          actual_departure: form.actual_departure || null,
          actual_arrival: form.actual_arrival || null,
          status: form.status,
        },
      });
      onOpenChange(false);
    } catch (err) {
      const { fieldErrors, message } = parseApiError(err);
      setErrors(fieldErrors ?? {});
      setGeneralError(message ?? "");
    }
  }

  const legLabel = trip?.round_number
    ? `Round ${trip.round_number} · ${trip.direction === "inbound" ? "return" : "outbound"}`
    : null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Edit Trip</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          {legLabel && (
            <p className="rounded-lg px-3 py-2 text-xs" style={{ background: "var(--surface-2)", color: "var(--text-muted)" }}>
              {legLabel} of a shift. Editing the shift's hours re-derives these times.
            </p>
          )}

          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label htmlFor="bus_id">Bus</Label>
              <Select
                value={form.bus_id ? String(form.bus_id) : ""}
                onValueChange={(v) => handleChange("bus_id", Number(v))}
              >
                <SelectTrigger id="bus_id" className="w-full">
                  <SelectValue placeholder="Select a bus" />
                </SelectTrigger>
                <SelectContent>
                  {buses.map((bus) => (
                    <SelectItem key={bus.id} value={String(bus.id)}>
                      {bus.plate_number}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {errors.bus_id && (
                <p className="mt-1 text-xs" style={{ color: "var(--critical)" }}>{errors.bus_id[0]}</p>
              )}
            </div>
            <div>
              <Label htmlFor="driver_id">Driver</Label>
              <Select
                value={form.driver_id ? String(form.driver_id) : ""}
                onValueChange={(v) => handleChange("driver_id", Number(v))}
              >
                <SelectTrigger id="driver_id" className="w-full">
                  <SelectValue placeholder="Select a driver" />
                </SelectTrigger>
                <SelectContent>
                  {drivers?.map((driver) => (
                    <SelectItem key={driver.id} value={String(driver.id)}>
                      {driver.first_name} {driver.last_name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {errors.driver_id && (
                <p className="mt-1 text-xs" style={{ color: "var(--critical)" }}>{errors.driver_id[0]}</p>
              )}
            </div>
          </div>

          <div>
            <Label htmlFor="trip_date">Trip date</Label>
            <Input
              id="trip_date"
              type="date"
              value={form.trip_date}
              onChange={(e) => handleChange("trip_date", e.target.value)}
              required
            />
            {errors.trip_date && (
              <p className="mt-1 text-xs" style={{ color: "var(--critical)" }}>{errors.trip_date[0]}</p>
            )}
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label htmlFor="departure_time">Planned departure</Label>
              <Input
                id="departure_time"
                type="time"
                value={form.departure_time}
                onChange={(e) => handleChange("departure_time", e.target.value)}
              />
              {errors.departure_time && (
                <p className="mt-1 text-xs" style={{ color: "var(--critical)" }}>{errors.departure_time[0]}</p>
              )}
            </div>
            <div>
              <Label htmlFor="arrival_time">Planned arrival</Label>
              <Input
                id="arrival_time"
                type="time"
                value={form.arrival_time}
                onChange={(e) => handleChange("arrival_time", e.target.value)}
              />
              {errors.arrival_time && (
                <p className="mt-1 text-xs" style={{ color: "var(--critical)" }}>{errors.arrival_time[0]}</p>
              )}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label htmlFor="actual_departure">Actual departure</Label>
              <Input
                id="actual_departure"
                type="datetime-local"
                value={form.actual_departure}
                onChange={(e) => handleChange("actual_departure", e.target.value)}
              />
            </div>
            <div>
              <Label htmlFor="actual_arrival">Actual arrival</Label>
              <Input
                id="actual_arrival"
                type="datetime-local"
                value={form.actual_arrival}
                onChange={(e) => handleChange("actual_arrival", e.target.value)}
              />
            </div>
          </div>

          <div>
            <Label htmlFor="status">Status</Label>
            <select
              id="status"
              value={form.status}
              onChange={(e) => handleChange("status", e.target.value)}
              className="w-full rounded-md border px-3 py-2 text-sm"
              style={{ borderColor: "var(--border)", background: "var(--surface)", color: "var(--text)" }}
            >
              {STATUSES.map((status) => (
                <option key={status} value={status}>
                  {status.charAt(0).toUpperCase() + status.slice(1)}
                </option>
              ))}
            </select>
            {errors.status && (
              <p className="mt-1 text-xs" style={{ color: "var(--critical)" }}>{errors.status[0]}</p>
            )}
          </div>

          {generalError && (
            <p className="text-sm" style={{ color: "var(--critical)" }}>
              {generalError}
            </p>
          )}

          <DialogFooter>
            <Button type="submit" disabled={updateTrip.isPending}>
              {updateTrip.isPending ? "Saving…" : "Save"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
